site_name: MathChain Wiki
site_description: In Math We Trust!
site_author: MathChain

site_url: http://docs.mathchain.org/
repo_url: https://github.com/mathwallet/docs.mathchain.org

dev_addr: 0.0.0.0:8000

copyright: Copyright &copy; 2018 MathChain

nav:
  - Home: index.md

  - 'Introduction':
    - 'MATH Token': en/token.md
    - 'Architecture': en/arch.md
    - 'Networks': en/networks.md
    - 'Launch Roadmap': en/launch.md
  - 'Testnet':
    - 'GaloisL1':
      - 'Run a Validator Node ': en/tut_run_node.md
      - 'Set up MathWallet': en/gmathwalletl1.md
      - 'Set up PolkadotJS': en/gpolkadotjs.md
      - 'Smart Web Wallet Guide': en/gwebwallet.md
      - 'Faucet': en/tut_testnet_faucet.md
      - 'Tools': en/tools.md
      - 'L1-L2 Swap': en/l1l2swap.md
      - 'API': en/substrate_api.md
      - 'SubQuery': en/subquery.md
      - 'SecretStore':
        - 'API': en/secretstore_api.md
        - 'SmartWallet': en/sequencechart.md
        - 'Security': en/security.md
    - 'GaloisL2':
      - 'Set up MathWallet': en/gmathwalletl2.md
      - 'Set up Metamask': en/gmetamask.md
      - 'Deploy a Smart Contract': en/smartcontract.md
      - 'Deploy MAT20 token': en/mat20.md
      - 'Deploy NFT token': en/nft.md
      - 'API': en/evm_api.md
      - 'GraphQL': en/graphql.md

plugins:
  - search

theme:
  name: 'material'
  palette:
    primary: 'White'
    accent: 'indigo'
  logo: 'images/logo.svg'

extra:
  manifest: 'manifest.webmanifest'
  social:
    # - icon: fontawesome/brands/github-alt
    #   link: 'https://github.com/mathwallet'
    # - icon: fontawesome/brands/twitter-alt
    #   link: 'https://twitter.com/mathwallet'
